log4j.rootLogger=WARN, stdout

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n

log4j.logger.kafka=WARN
log4j.logger.kafka.server.KafkaServer=WARN
log4j.logger.kafka.controller=WARN
log4j.logger.kafka.controller.KafkaController=WARN
log4j.logger.kafka.controller.ControllerChannelManager=WARN
log4j.logger.kafka.controller.ControllerEventManager$ControllerEventThread=WARN
log4j.logger.kafka.controller.RequestSendThread=WARN
log4j.logger.kafka.controller.ZkReplicaStateMachine=WARN
log4j.logger.kafka.controller.ZkPartitionStateMachine=WARN
log4j.logger.kafka.log.LogCleaner=WARN
log4j.logger.kafka.log.LogManager=WARN
log4j.logger.kafka.log.UnifiedLog$=WARN
log4j.logger.kafka.cluster.Partition=WARN
log4j.logger.kafka.coordinator.group.GroupCoordinator=WARN
log4j.logger.kafka.coordinator.group.GroupMetadataManager=WARN
log4j.logger.kafka.coordinator.group.GroupMetadata$=WARN
log4j.logger.kafka.server.BrokerToControllerRequestThread=WARN
log4j.logger.kafka.server.ClientQuotaManager$ThrottledChannelReaper=WARN
log4j.logger.kafka.server.DelayedOperationPurgatory$ExpiredOperationReaper=WARN
log4j.logger.kafka.server.ReplicaFetcherManager=WARN
log4j.logger.kafka.network.SocketServer=WARN
log4j.logger.kafka.network.DataPlaneAcceptor=WARN
log4j.logger.kafka.zk.KafkaZkClient=WARN
log4j.logger.state.change.logger=WARN
log4j.logger.org.apache.kafka=WARN
log4j.logger.org.apache.zookeeper=WARN
